### PR TITLE
[14.0][IMP] intrastat_product: Add read access to intrastat lines to …

### PR DESCRIPTION
**Pull request by rousseldenis**
…accounting base user

### CODE REVIEW

**Comment by rousseldenis** [comment]
If user has access to invoices but not intrastat lines, access error is raised.

**Review by flotho — APPROVED** [review]
easy code Review LGTM
thanks

**Comment by rousseldenis** [comment]
@flotho I've added sale and purchase users too as they have access to invoices.

**Review by flotho — APPROVED** [review]
LGTM

**Review by luc-demeyer — APPROVED** [review]

**Pull request merged**
