### PR TITLE
[17.0][FIX]intrastat_product: fix `migrate` method params

### PR DESCRIPTION
**Pull request by GuillemCForgeFlow**
Fixes migration script introduced in https://github.com/OCA/intrastat-extrastat/pull/286

cc @ForgeFlow

### CODE REVIEW

**Comment by GuillemCForgeFlow** [comment]
@victoralmau @pedrobaeza @carlos-lopez-tecnativa I guess we can have this merged?

**Comment by pedrobaeza** [comment]
Uhm, it was correct before. It has the decorator `openupgrade.migrate()`, and that's why it's `env`, and not `cr`.

**Comment by GuillemCForgeFlow** [comment]
> Uhm, it was correct before. It has the decorator `openupgrade.migrate()`, and that's why it's `env`, and not `cr`.

I see now, strange it is failing for my case. Will check in more detail and get back 👍🏿

**Comment by GuillemCForgeFlow** [comment]
@pedrobaeza I see that starting from v17, the `env` param should be used instead right? https://github.com/OCA/openupgradelib/blob/master/openupgradelib/openupgrade.py#L297 - https://github.com/OCA/openupgradelib/blob/master/openupgradelib/openupgrade.py#L320

**Review by pedrobaeza — APPROVED** [review]
OK now.

**Pull request merged**
