### PR TITLE
[13.0][IMP] intrastat_product - add notedict to some methods

### PR DESCRIPTION
**Pull request by ghost**
I add the notedict dictionary on some methods to allow in our l10n_be_intrastat_product_declaration module (https://github.com/OCA/l10n-belgium/blob/14.0/l10n_be_intrastat_product/models/l10n_be_intrastat_product_declaration.py#L48) to adapt our backport to v13 to fit with the changes made in the PR #179 (https://github.com/OCA/intrastat-extrastat/blob/13.0/intrastat_product/models/intrastat_product_declaration.py#L766)

### CODE REVIEW

**Review by luc-demeyer — CHANGES_REQUESTED** [review]
changing the signature of the methods will break the localisation modules.
I suggest to change it to e.g.
def _get_intrastat_transaction(self, inv_line, notedict=None)

**Comment by pedrobaeza** [comment]
The same problem will happen with keyword arguments. The only solution I see now for this version is to pass the variable by context.

**Comment by luc-demeyer** [comment]
@pedrobaeza 
The problem starts with https://github.com/OCA/intrastat-extrastat/pull/179 where not only the brexit but also the 'notedict' changes have been backported to 13.0 resulting in broken french and belgian localisation modules. We cannot revert it back since otherwise we'll break the spanisch 13.0 l10n_es_intrastat_report.
In order to move forward I propose following actions
1) we backport the 'notedict' based l10n_be_intrastat_product from 14.0 to 13.0
2) we do the same for l10n_fr_intrastat_product

@alexis-via 
Do you agree with this approach ? We'll backport the french module and test it.
We count on you for review and merge.

**Comment by pedrobaeza** [comment]
If you change all the OCA involved modules, OK then.

**Comment by luc-demeyer** [comment]
I am only aware of
-  l10n_fr_intrastat_product
-  l10n_es_intrastat_report
-  l10n_be_intrastat_product
We'll cover these.

**Comment by pedrobaeza** [comment]
Ok

**Comment by alexis-via** [comment]
@luc-demeyer ok. I don't use v13 myself, so it's not a big deal for me.

**Review by victoralmau — APPROVED** [review]
Changes seem to make sense.

**Comment by pedrobaeza** [comment]
@jdidderen-be please squash both commits into one.

**Comment by ghost** [comment]
> @jdidderen-be please squash both commits into one.

@pedrobaeza Commits are squashed

**Comment by pedrobaeza** [comment]
@luc-demeyer is it OK for you?

**Comment by ghost** [comment]
@luc-demeyer @pedrobaeza This PR is now closed because I didn't followup. The PR https://github.com/OCA/l10n-france/pull/401 in the french localization is also in the same state. The only one still alives is the one from the spanish localization https://github.com/OCA/l10n-spain/pull/2711. 

What should we do ?

**Comment by pedrobaeza** [comment]
You can resubmit another PR with the same branch.

**Pull request closed without merging**
