### PR TITLE
[FIX] intrastat_product: fix error creating intrastat product declara…

### PR DESCRIPTION
**Pull request by rafael-petrella**
…tion when missing Country of Origin/Destination

### CODE REVIEW

**Review by luc-demeyer — APPROVED** [review]

**Review by pedrobaeza — APPROVED** [review]

**Comment by pedrobaeza** [comment]
Is this applicable to upper versions?

**Comment by luc-demeyer** [comment]
@pedrobaeza 
yes. it would be usefull to cherry-pick this fix to 14.0 and 15.0 PR.

**Comment by pedrobaeza** [comment]
@rafael-petrella Can you please do the PRs to upper versions?

**Pull request merged**
