### PR TITLE
[15.0][MIG] intrastat_product: Migration to 15.0

### PR DESCRIPTION
**Pull request by victoralmau**
Migration to 15.0

Locked by:
- [x] `product_harmonized_system` https://github.com/OCA/intrastat-extrastat/pull/186

Superseed https://github.com/OCA/intrastat-extrastat/pull/165

@Tecnativa TT36959

### CODE REVIEW

**Comment by pedrobaeza** [comment]
Please rebase

**Comment by victoralmau** [comment]
Rebase done, it's ready to review

**Review by pedrobaeza — APPROVED** [review]
Please update at least Spanish translation

**Comment by victoralmau** [comment]
Spanish translation updated.

**Comment by pedrobaeza** [comment]
@luc-demeyer @alexis-via is it ok for you?

**Comment by pedrobaeza** [comment]
Let's merge this finally for unblocking other dependent things:

/ocabot merge nobump

**Pull request merged**
