### PR TITLE
[13.0][IMP] intrastat_product - add notedict to some methods

### PR DESCRIPTION
**Pull request by ghost**
See old PR https://github.com/OCA/intrastat-extrastat/pull/206 for the discussions around these changes.

PRs in the localization repositories :

- https://github.com/OCA/l10n-spain/pull/2711
- https://github.com/OCA/l10n-france/pull/465

### CODE REVIEW

**Comment by ghost** [comment]
@pedrobaeza @luc-demeyer @alexis-via The PR was recreated since the old one https://github.com/OCA/intrastat-extrastat/pull/206 went stale. I did the same for the PR in the french localization.

**Review by pedrobaeza — APPROVED** [review]

**Review by victoralmau — APPROVED** [review]

**Comment by victoralmau** [comment]
IMO this is ready to be merged.

**Review by luc-demeyer — APPROVED** [review]

**Comment by pedrobaeza** [comment]
Please fw-port it to upper versions:

/ocabot merge patch

I'll merge the subsequent PRs as soon as this one gets merged.

**Comment by GuillemCForgeFlow** [comment]
Hi @pedrobaeza this change caused issues on one of our installations due to adding new arguments in the methods. Is this a common practice in the OCA?

**Comment by pedrobaeza** [comment]
No, it's not, but it wasn't the less bad option due to the incorrect previous situation after Brexit code. See this thread and the source one #206 for details (you should do it before writing, as it's all linked), and all the OCA modules were patched with the new arguments thanks to @jdidderen-noviat diligence. Only custom things outside OCA should be affected, and it's very easy to fix and detect (no silent problems, but direct crash).

**Pull request merged**
