### PR TITLE
[8.0] Add intrastat v3

### PR DESCRIPTION
**Pull request by alexis-via**
This PR is just a move of the initial PR on account-financial-reporting https://github.com/OCA/account-financial-reporting/pull/80

Thanks to our git-fu @sylvain-garancher for the transition.

### CODE REVIEW

**Comment by pedrobaeza** [comment]
I know that you hate this, but can you squash the commits a bit to avoid a hundred of them?

**Comment by alexis-via** [comment]
No

**Comment by alexis-via** [comment]
We have 5 years of work on these modules, so no surprise the git history is a bit long !

**Comment by pedrobaeza** [comment]
I know that, but at least you can admit that commits like "Warning -> UserError" are not relevant for the history. Please review it and reduce a bit for me.

**Comment by alexis-via** [comment]
I don't have time to play with that. I have an enormous amount of work to port many OCA modules to v10 before 1/1/2017. Sorry.

**Comment by luc-demeyer** [comment]
Thanks Alexis.
Imho this PR is ready for merge so that we can proceed with the PR's for the localisation modules.

**Comment by alexis-via** [comment]
The initial PR had 2 approve, so let's merge this one. Runbot is red only because it lacks stock-logitics-workflow.  Travis is green.

**Pull request merged**
