### PR TITLE
[13.0] intrastat_product: Add xml_attachment_id field and various improvements

### PR DESCRIPTION
**Pull request by alexis-via**
intrastat_product: add mail.activity.mixin and widget in form view
product_harmonized_system: remove archive button (use Action menu)
All modules:
- use super() instead of super(class, self)
- Update domain_force in multi-company ir.rule to v13 standard

### CODE REVIEW

**Review by luc-demeyer — APPROVED** [review]
Code review  & testing ok.
Nice work, imho we should merge this one asap.
Adding a migration script for the company record rule would be a usefull but this is not blocking for me.

**Review by pedrobaeza — CHANGES_REQUESTED** [review]
The change in record rules requires migration script. See https://github.com/OCA/maintainer-tools/wiki/Migration-to-version-13.0#tasks-to-do-in-the-migration for an example

**Comment by alexis-via** [comment]
Here they are!

**Review by pedrobaeza — APPROVED** [review]

**Pull request merged**
