### PR TITLE
[18.0][MIG] product_harmonized_system_stock: Migration to 18.0

### PR DESCRIPTION
**Pull request by LucasTran380381**
Depend: https://github.com/OCA/intrastat-extrastat/pull/288

### CODE REVIEW

**Review by henrybackman — APPROVED** [review]

**Review by ajaniszewska-dev — APPROVED** [review]

**Review by alexis-via — APPROVED** [review]

**Comment by StefanRijnhart** [comment]
Please remove the test dependency.

**Comment by LucasTran380381** [comment]
> Please remove the test dependency.

removed

**Comment by StefanRijnhart** [comment]
Please also resolve the conflict.

**Pull request merged**
