### PR TITLE
change m2m table name to avoid naming conflicts with other modules

### PR DESCRIPTION
**Pull request by luc-demeyer**
cf. https://github.com/OCA/intrastat-extrastat/issues/97

### CODE REVIEW

**Review by pedrobaeza — CHANGES_REQUESTED** [review]
You need to add a migration script that rename previous table, or does that table already exists before this module?

**Comment by matteoopenf** [comment]
> You need to add a migration script that rename previous table, or does that table already exists before this module?

I think is not possible in this specific  case

**Review by matteoopenf — APPROVED** [review]

**Comment by luc-demeyer** [comment]
@pedrobaeza 
I agree that in principle a migration script would be needed but in reality I have no single customer using this option (hence no impact) and I doubt that there are installation having more than 1 or 2 of such users (hence spending time on such a migration script is not high on my priority list but I agree it's also not a lot of work).

**Comment by pedrobaeza** [comment]
OK, me neither, but I prefer to be totally correct, but if you think we should go ahead, then I refrain my review.

**Review by alessandrocamilli — APPROVED** [review]

**Comment by matteoopenf** [comment]
Hi @alexis-via merge?

**Pull request merged**
