### PR TITLE
[10.0] intrastat_product: fix crash in XLS export when there is empty data in compute line

### PR DESCRIPTION
**Pull request by alexis-via**

### CODE REVIEW

**Review by luc-demeyer — APPROVED** [review]

**Comment by luc-demeyer** [comment]
@pedrobaeza 
I tried the /ocabot merge on this small PR but the Travis CI build fails.
How should I proceed ?

**Comment by pedrobaeza** [comment]
That's because the result is red. I have fixed the main branch in fee98cea2346277b64158b089e76a0696ea8e969, so let's see if now the result is correct:

/ocabot merge patch

**Comment by luc-demeyer** [comment]
@pedrobaeza 
thanks a lot for fixing the travis.yml.

**Pull request merged**
