### PR TITLE
[IMP] intrastat_product - remove default company for intrastat regions

### PR DESCRIPTION
**Pull request by ghost**
Right now, regions have a company by default but if we have two belgian companies or two french companies, it's not logical to have the regions declared in each company nor "user-friendly" to have to edit default regions on the "first" company to have it on each company. 

For example, while migrating l10n_be_intrastat_product and testing on an empty database, my regions were created in one company and not available on the second belgian company. I had to go on the first company to edit the regions and make it available for the second one.

### CODE REVIEW

**Review by luc-demeyer — APPROVED** [review]
The localisation modules should set the regions based upon the country_id.
I suggest that the localisation modules inherit from the accounting setup wizard In order to ensure that this is also the case when adding a new company.

**Comment by pedrobaeza** [comment]
There seems to be something weird with the READMEs digest.

**Comment by ghost** [comment]
@pedrobaeza These changes were made by pre-commit. I let it passed since I was not sure it's intended or not. 
Should I remove these ?

**Review by pedrobaeza — APPROVED** [review]
I have downloaded the branch locally, undoing the digest changes, and they are not done. I think you have an old tooling in your local. Please update it.

As this is now fixed, merging it:

/ocabot merge patch

**Pull request merged**
