### PR TITLE
[14.0][MIG] intrastat_product_generic

### PR DESCRIPTION
**Pull request by rousseldenis**
@luc-demeyer

### CODE REVIEW

**Comment by luc-demeyer** [comment]
@rousseldenis 
thanks for migrating this module.
I'll review this PR.

If you have time: please feel free to port https://github.com/Noviat/noviat-apps/tree/13.0/l10n_be_intrastat_product to 14.0 and push it to the oca/l10n-belgium repo.
If you don't have time than I'll do it (with as absolute deadline the first belgian 2022 intrastat declaration, hence feb 20, 2022 since otherwise I will be killed by a couple of customers). There is a bit of work though since both the brexit changes and the 2022 NBB/BNB intrastat changes must be implemented.   The l10n_be_intrastat_product is also missing unit ttests which is the main reason why I haven't pushed this module to the oca/l10n-belgium yet.

**Comment by rousseldenis** [comment]
> @rousseldenis thanks for migrating this module. I'll review this PR.
> 
> If you have time: please feel free to port https://github.com/Noviat/noviat-apps/tree/13.0/l10n_be_intrastat_product to 14.0 and push it to the oca/l10n-belgium repo. If you don't have time than I'll do it (with as absolute deadline the first belgian 2022 intrastat declaration, hence feb 20, 2022 since otherwise I will be killed by a couple of customers). There is a bit of work though since both the brexit changes and the 2022 NBB/BNB intrastat changes must be implemented. The l10n_be_intrastat_product is also missing unit ttests which is the main reason why I haven't pushed this module to the oca/l10n-belgium yet.

My customer is not in Belgium, so... :-)

**Review by luc-demeyer — APPROVED** [review]
code review & testing ok.

**Pull request merged**
