### PR TITLE
[14.0][MIG]hs_code_link: Migration to 14.0

### PR DESCRIPTION
**Pull request by GuillemCForgeFlow**
This module depends on the product_harmonized_system, as it has been migrated, the hs_code_link module can be migrated.
@ForgeFlow

### CODE REVIEW

**Review by ChrisOForgeFlow — APPROVED** [review]
+1

**Comment by alexis-via** [comment]
Please use the module product_harmonized_system_delivery which is already available for v14 https://github.com/OCA/intrastat-extrastat/tree/14.0/product_harmonized_system_delivery

**Comment by GuillemCForgeFlow** [comment]
> Please use the module product_harmonized_system_delivery which is already available for v14 https://github.com/OCA/intrastat-extrastat/tree/14.0/product_harmonized_system_delivery

I'm not sure to understand what you mean, in branch there's already the product_harmonized_system_delivery module, do you mean that this module already does the funcionalitiy of the hs_code_link module?
Thanks.
@alexis-via

**Comment by alexis-via** [comment]
@GuillemCForgeFlow Yes

**Pull request closed without merging**
