### PR TITLE
[14.0] intrastat_base: use fiscal position

### PR DESCRIPTION
**Pull request by alexis-via**
Please wait for the PR of the migration of intrastat_product to v14 before merging, because I may need to introduce other changes.

### CODE REVIEW

**Review by luc-demeyer — CHANGES_REQUESTED** [review]
please adapt USAGE.rst to reflect changed fields (fiscal postion boolean i.s.o. country boolean and flag on taxes)

**Review by luc-demeyer — APPROVED** [review]

**Comment by pedrobaeza** [comment]
I don't get why it's better to remove the flag on countries and put it on fiscal positions. This makes the need to add a localization module to each country and see if there's a FP that matches the requirement. Can you explain the reasons?

**Comment by luc-demeyer** [comment]
@pedrobaeza : it's explained in issue https://github.com/OCA/intrastat-extrastat/issues/110

**Comment by pedrobaeza** [comment]
I see, but the problem I depicted is still there, so I propose a mixed formula: keep country flag, but give more priority to fiscal position one.

**Comment by luc-demeyer** [comment]
Keeping the country flag doesn't make a lot of sense since the query on the fiscal position is one that gives the correct result.
A query on country may result in deviating intrastat and tax reports and usually the tax reports are the correct ones.
A country flag fallback logic will make the whole thing imho only more confusing and increase risk on misconfiguration.
The localisation modules require a small change if they want to set the intrastat flag on the fiscal position but without this change if will still work if the user reads the intrastat "README.rst" and configures this flag manually.

**Comment by pedrobaeza** [comment]
It's not a small change, as this impact on both existing installations + new, as the fiscal position is generated for each company. I prefer this change to not be applied, or not without explicit opt-in, and let the previous one as fallback.

**Comment by luc-demeyer** [comment]
@pedrobaeza 
technically it is easy to add the boolean for each company in a migration script:

for company in companies:
    fpos_ref = "{}.{}_{}".format(module.name, .company.id, fpt_name)
   ...

companies: all spanish companies in a database.
module = 'l10n_es'
fpt_name = xml_id name of the intra community fiscal position

If you leave the country flag than you hit the problem of wrong declaration entries for e.g. B2C customers in those countries.
If we remove it completely and your customer has created his own fiscal position (and not the one from the localisation module) than he will see an empty declaration and realise that something is wrong (hence call his integrator or read the module info and set the flag).

Haviing a simple boolean on the intracomm fiscal position is the easiest way to configure this and at the same time it handles the brexit case. 
It is a change but a lot smaller than the type of changes made by Odoo when they create a new version.

You can of course still add a country-based fallback in the spanish localisation module and maintain the table of EU-intrastat countries at that place but I don't recommend since it does not cover the brexit case and it adds imho only complexity and confusion.

@alexis-via 
What do you think ?

**Comment by pedrobaeza** [comment]
OK, it's not ideal due to what I have commented, but I understand the use case, and I will try to add at Spanish Intrastat glue module the automatic checking of the mark for the proper Spanish fiscal position.

/ocabot merge major

**Comment by alexis-via** [comment]
Seems the merge bot is dead. How should we proceed @pedrobaeza ?

**Pull request merged**
