### PR TITLE
[FIX] 2 critical bugs

### PR DESCRIPTION
**Pull request by alexis-via**
@luc-demeyer An easy fix to review :)

### CODE REVIEW

**Comment by alexis-via** [comment]
@luc-demeyer There are 2 easy fixes here. Could you review, so that I can merge it then ?

**Review by pedrobaeza — APPROVED** [review]
I fast-track this as obvious and dangerous because of the related, but please change module version number

**Review by rvalyi — APPROVED** [review]

**Comment by moylop260** [comment]
@pedrobaeza FYI I just edited the manifest file from github interface and bumped version before to merge.

**Comment by luc-demeyer** [comment]
merged before I found the time to review (I am too slow sorry) but of course I agree with the weigt_net -> weight change as well as the country_id readonly.
Thanks for merging this PR.

**Pull request merged**
