### PR TITLE
[11.0][MIG]intrastat_product

### PR DESCRIPTION
**Pull request by luc-demeyer**
This PR replaces https://github.com/OCA/intrastat-extrastat/pull/47 which has become a bit messy.
This PR has been fully tested via the generic product declaration and belgian localization module (cf. https://github.com/luc-demeyer/noviat-apps/tree/11.0/l10n_be_intrastat_product).

@alexis-via 
I have included in this PR the following commits which you made after my PR against the Akretion branch
- Add readonly on some fields when state of declaration is done
- [FIX] Division by zero in computation of accessory costs

I propose that you add the new module  product_harmonized_system_delivery once this one is merged.

### CODE REVIEW

**Comment by alexis-via** [comment]
I think we have a big pb with this PR that got merged in OCA/11.0: it shows 4 commits that all belong to Luc de Meyer, but when you see the diff, it adds ALL (or a very large part of) the module intrastat_product, which is obviously not true, because this module was co-developped by Luc and me several years ago. So I think we have a problem in the history now.
@luc-demeyer @rvalyi What do you think ?

**Comment by alexis-via** [comment]
BTW, we need to do a better job when porting to v12 than the mess we did for the v11 port, with a very bad coordination.
I was planning to do the port to v12 this week, but as I discovered this problem and the fact that my code was not merged in OCA/11.0 on intrastat-extrastat, I delayed this work (in the current situation, OCA/l10n-france doesn't work with OCA/11.0... this is really a problem).
I propose the following plan:
1) sort out and fix the problems in OCA/11.0: fix history and get my work merged (so that OCA/l10n-france/11.0 works with OCA/intrastat/11.0)
2) I delete the current 12.0 branch
3) I do a full port (all modules) from 11.0 to 12.0
4) once the full port is merged, then you can improve the 12.0 branch if you need.

**Comment by pedrobaeza** [comment]
This PR was auto-merged by @luc-demeyer himself without reviews nor preserving commit history according migration guide (https://github.com/OCA/maintainer-tools/wiki/Migration-to-version-11.0), so the options are:

- Revert this and start again preserving commit story. Very dirty with diff size.
- Fix the history resetting the repository previous to the merge, and make a PR with the commit history, and the changes for v11 from Luc on top. This will preserve the repository, but forces to reset the repository on already downloaded branches.

**Comment by alexis-via** [comment]
@pedrobaeza I think your second proposal is OK. This project is not widely used and we can send a mail to the OCA mailing-list to warn users to re-download that branch. How should we proceed ? I can take care of doing the new PR with the commit history.

**Comment by pedrobaeza** [comment]
OK, then I reset the branch to the previous state. Please see if you can compatibilize your branch with Luc's improvements.

**Comment by alexis-via** [comment]
I deleted the 12.0 branch, so that we will re-create it from 11.0 once the 11.0 branch will be fixed.

**Comment by pedrobaeza** [comment]
That wasn't needed AFAIK, as now the branches are created empty, but no problem in re-create it.

**Comment by pedrobaeza** [comment]
I'm going to wait any way as courtesy to @luc-demeyer's answer

**Comment by luc-demeyer** [comment]
@pedrobaeza 

I agree with your second proposal:
"
Fix the history resetting the repository previous to the merge, and make a PR with the commit history, and the changes for v11 from Luc on top. This will preserve the repository, but forces to reset the repository on already downloaded branches.
"
Since there are companies out there running with this code, could you ensure that both operations (restore to previous level + reapply current versions of the modules) are executed at the same time to minimise  the risk that someone performs a git pull and retrieves a set of modules which are not equal to the current set of published 11.0 modules.
I also had a call with Alexis this afternoon. This approach is ok for him.
We'll also synchronise a bit better our porting work to 12.0

**Comment by pedrobaeza** [comment]
Well, for synchronizing both things, one of you have to make the PR and being reviewed and valid (but having merge conflicts), and then, I reset the branch and merge, but the solution without this is also simply: if they do `git pull`, there won't be new commits, as this has been reset to previous HEAD, and thus, they won't lose anything, so I think it's safe to reset first.

The conflict will arise when we merge the PR, that doing `git pull`, it will fail, and they will need to reset the branch as said.

**Comment by luc-demeyer** [comment]
I don't understand it fully but that's because git isn't my area of expertise.
Since (to my understanding) the real issue is that we lost the history on intrastat_product: is there no method to just copy the 10.0 git history into the current 11.0 branch.

I am thinking on something like 
- $ git checkout -b 11.0-mig-<module> origin/11.0
- $ git format-patch --keep-subject --stdout origin/11.0..origin/10.0 -- <module path> | git am -3 --keep
This gives a local branch with the whole 10.0 history in it.
Can we somehow carve the intrastat_product history out of that one, commit the currently publised 11.0 intrastat_product  module on top of that one and than make a PR towards the current branch and merge it so that we have a restored commit history (and hopefully avoid the need for a branch reset).

**Comment by alexis-via** [comment]
I'm not good enough on git to help on this, but we need to move forward. I would really like to fix this in the coming days.

**Comment by pedrobaeza** [comment]
@alexis-via just follow the instructions. It's pretty straightforward. If you have any doubt, just tell us.

**Comment by alexis-via** [comment]
What I can propose on my side : start from akretion's branch "11.0-mig-intrastat_product" https://github.com/akretion/intrastat-extrastat/commits/11.0-mig-intrastat_product that has a good history, then compare with the code currently in OCA/11.0 and add it with Luc as author, and then do a PR on OCA/11.0.
@luc-demeyer Are you OK with my proposal ?

**Comment by luc-demeyer** [comment]
In that case I'll actualize my PR that I have already made towards this branch. After merging my PR into this branch we can reset HEAD, merge the branch and we'll be ready for the 12.0 port.

**Comment by pedrobaeza** [comment]
OK, proceed and I'll reset the 11.0 branch when the PR is done.

**Comment by luc-demeyer** [comment]
@alexis-via 
please review https://github.com/akretion/intrastat-extrastat/pull/3. Once this one is merged into https://github.com/akretion/intrastat-extrastat/commits/11.0-mig-intrastat_product we can go ahead with the reset of the branch.

**Comment by alexis-via** [comment]
@luc-demeyer your PR is now merged. I re-opened akretion's PR for v11 https://github.com/OCA/intrastat-extrastat/pull/47
What is the next step ?

**Comment by luc-demeyer** [comment]
@pedrobaeza 
It looks like we are now ready for the reset of of 11.0 branch and merge of this PR.

**Comment by pedrobaeza** [comment]
I have asked in #47, as now I'm not sure what to exactly do.

**Pull request merged**
