### PR TITLE
[17.0][MIG] product_harmonized_system_stock

### PR DESCRIPTION
**Pull request by AndreuOForgeFlow**
Standard migration

Please, see this FIX PR before merging this module for optimal use: https://github.com/OCA/intrastat-extrastat/pull/268

@ForgeFlow

### CODE REVIEW

**Review by GuillemCForgeFlow — APPROVED** [review]
LGTM 👍🏿

**Review by CarlosVForgeFlow — APPROVED** [review]
LGTM

**Comment by GuillemCForgeFlow** [comment]
Hi @alexis-via I guess this is ready to be merged, right? 😄

**Comment by AndreuOForgeFlow** [comment]
Hi @alexis-via, I guess this module is ready to be merged? Also, we could add it to the Migration ToDo list.

**Pull request merged**
