### PR TITLE
[16.0][ADD] intrastat_delivery

### PR DESCRIPTION
**Pull request by aritzolea**

### CODE REVIEW

**Review by SoniaViciana — APPROVED** [review]
Functional review LGTM

imagen

**Review by ghost — APPROVED** [review]
LGTM

**Comment by ghost** [comment]
Please add [16.0] to the PR title.

**Review by pedrobaeza — CHANGES_REQUESTED** [review]
Module names shouldn't contain plurals, and they should also reflect original module names, so I suggest to call it `intrastat_delivery`.

**Review by pedrobaeza — APPROVED** [review]
/ocabot merge nobump

**Pull request merged**
