### PR TITLE
[13.0][instrastat_product][fix] method get_hs_code_recursively

### PR DESCRIPTION
**Pull request by JordiBForgeFlow**
This method belongs to product.product not to move.line

### CODE REVIEW

**Review by luc-demeyer — CHANGES_REQUESTED** [review]
should be:

     rec.hs_code_id = intrastat_line.hs_code_id or rec.product_id.get_hs_code_recursively()

**Comment by JordiBForgeFlow** [comment]
Thanks @luc-demeyer. Fixed!

**Review by alexis-via — APPROVED** [review]

**Review by luc-demeyer — APPROVED** [review]

**Comment by luc-demeyer** [comment]
replaced by https://github.com/OCA/intrastat-extrastat/pull/151

**Pull request closed without merging**
