### PR TITLE
11.0 mig intrastat product

### PR DESCRIPTION
**Pull request by rvalyi**
supersedes https://github.com/OCA/intrastat/pull/30
and

- rebase on 11.0 so it includes the intrastat_base module
- cherry pick view fix from v10: https://github.com/OCA/intrastat/pull/42
- cherry pick get_hs_code_recursively on product.template form v10: https://github.com/OCA/intrastat/pull/46

However tests won't pass here yet as it depends on the product_harmonized_system to be merged here:
https://github.com/OCA/intrastat/pull/38

### CODE REVIEW

**Comment by luc-demeyer** [comment]
Thanks for this PR.

Two bugs that we shouldn't carry forward (and review/merge asap in the 8.0 and 10.0 repos):
- intrastat_base: include https://github.com/OCA/intrastat/pull/43
- intrastat_product: include https://github.com/OCA/intrastat/pull/39

I also think that we broken code repaired by the 'get_hs_code_recursively' fixes has painfully demonstrated that we need unit test on this module. It would be great if you could add this.

**Comment by rvalyi** [comment]
@luc-demeyer I rebased on 11.0 so tests are green. Also I cherry-picked #43 and #39 as you requested.
So far, compared to v10, we are missing #41. But may be we could merge and do a PR to port de xmls reporting later. Indeed this is not a trivial cherry pick so it make take more time and may be it would be better to have this PR already merged meanwhile. What do you think?

**Comment by luc-demeyer** [comment]
@rvalyi 
Thanks a lot. I'll make a PR on top of your PR to include the generic reporting (#41). 
The advantage of doing so is that the generic report allows to test this module independent of the localisations modules (as a next step we should spend a bit of time to add unit tests).

**Comment by luc-demeyer** [comment]
@rvalyi 
cf. https://github.com/akretion/intrastat/pull/2
Can you review and merge ?
I went through the latest fixes on the 10.0 branch and included them.
You all see a bunch of small enhancement and code style improvements.
I tested it with the generic declaration and could generate the computation & declaration lines and the excel reports.
Imho we are to merge this so that we can test & publish our localisation modules.

@alexis-via 
Please review if I didn't miss anything with the addition of the recent 10.0 fixes.

**Comment by luc-demeyer** [comment]
@alexis-via 
we are not going to get there this way. 
First https://github.com/akretion/intrastat-extrastat/pull/2 should be merged (hence revert your latest changes and reapply them after this merge). My PR contains major changes in most files hence should be merged first in stead of increasing the number of conflicts.

**Comment by alexis-via** [comment]
yes, I just need to find time (which is not so easy to find !). But I'll do it...

**Comment by pedrobaeza** [comment]
@rvalyi please only one module per PR, and squash a bit the commit history by author/logical set.

**Comment by pedrobaeza** [comment]
You have also conflicting files.

**Comment by luc-demeyer** [comment]
Closing since superceeded by https://github.com/OCA/intrastat-extrastat/pull/62.

**Comment by pedrobaeza** [comment]
@alexis-via can this be merged as is? How did you solve conflicts?

**Comment by luc-demeyer** [comment]
I reapplied the latest published modules on top of this original PR from Akretion hence we have again the full commit history. Alexis reviewed it and merged the codes in this PR hence you can go ahead with the reset of the head to the point just before this PR and merge this one.

**Comment by pedrobaeza** [comment]
The weird thing is that this PR doesn't have conflicts with base branch, so in any sense, there's no need to reset the branch, but I want to know why before merging and have a mixed history. Or it's only an illusion as you have re-opened the PR?

**Comment by luc-demeyer** [comment]
A mixed history will probably be confusing.
@alexis-via : do you prefer merge with mixed history or merge after reset branch (clean history but requires 'force' when someone needs to update his local branche).

**Comment by alexis-via** [comment]
@luc-demeyer I don't mind, but I have a small preference for a clean history, even if it requires a force when updating.

**Comment by luc-demeyer** [comment]
@pedrobaeza 
can you go ahead (with reset branch) ?

**Comment by pedrobaeza** [comment]
OK, reset main branch done, and rebase over this branch. I have to unscramble the commit history due to several merge operations on the branches, so it has been quite some work. I have taken the occasion to squash commit history.

Merging when CIs finish in this PR. Please respect this on the 12.0 commit history when proposing the PR.

**Comment by luc-demeyer** [comment]
@pedrobaeza 
Thanks a thousand times.

**Comment by pedrobaeza** [comment]
You're welcome

**Pull request merged**
